version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:2345
    volumes:
      - .:/deepl_poc
    env_file: .env
    container_name: deepl_poc
    security_opt:
      - seccomp:unconfined
    depends_on:
      database:
        condition: service_healthy

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_HOST: "%"
    container_name: deepl-poc-db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 33069:3306
    volumes:
      - deepl_poc_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: "1s"
      timeout: "10s"
      retries: 10
      start_period: "1s"

  adminer:
    image: dockette/adminer:dg
    environment:
      - “MEMORY=512M”
    ports:
      - ${ADMINER_PORT}:80

volumes:
  deepl_poc_db:
